[travis-ci] Use the Release scheme instead of GitX
$ xctool -project GitX.xcodeproj -scheme GitX build test
ERROR: Can't find scheme 'GitX'.
Possible schemes include:
  Debug
  Release
The command "xctool -project GitX.xcodeproj -scheme GitX build test" exited with 1.